Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Import Dataset

In [ ]:
df = pd.read_csv('car.csv')
df

userid  gender  age  income  purchase
0   123456780    male   19   19000         0
1   123456781    male   25   20000         0
2   123456782  female   26   43000         0
3   123456783  female   27   57000         0
4   123456784    male   19   76000         0
5   123456785    male   27   58000         0
6   123456786  female   27   84000         0
7   123456787  female   32  190000         1
8   123456788    male   25   33000         0
9   123456789  female   35   65000         0
10  123456790  female   26   80000         0
11  123456791  female   26   25000         0
12  123456792    male   20   26000         0

Create value for x and y

In [ ]:
X = df.iloc[:,[2,3]].values
y = df.iloc[:,-1].values

Train and test the dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [ ]:
print(X_train)

[[    26  43000]
 [    25  33000]
 [    25  20000]
 [    32 190000]
 [    35  65000]
 [    27  57000]
 [    19  19000]
 [    27  58000]
 [    20  26000]]


In [ ]:
print(X_test)

[[   27 84000]
 [   26 25000]
 [   19 76000]
 [   26 80000]]


In [ ]:
print(y_train)

[0 0 0 1 0 0 0 0 0]


In [ ]:
print(y_test)

[0 0 0 0]


Perfom Feature scaling operation

In [ ]:
from sklearn.preprocessing import StandardScaler
obj = StandardScaler()
X_train = obj.fit_transform(X_train)
X_test = obj.transform(X_test)

In [ ]:
print(X_train)
print()
print(X_test)

[[-0.04649906 -0.27679123]
 [-0.25574481 -0.47768809]
 [-0.25574481 -0.73885401]
 [ 1.20897544  2.67639263]
 [ 1.83671269  0.16518186]
 [ 0.16274669  0.00446437]
 [-1.5112193  -0.7589437 ]
 [ 0.16274669  0.02455406]
 [-1.30197355 -0.61831589]]

[[ 0.16274669  0.5468859 ]
 [-0.04649906 -0.63840558]
 [-1.5112193   0.38616841]
 [-0.04649906  0.46652716]]


Create a model

In [ ]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()

Train the model

In [ ]:
regressor.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

predict the model

In [ ]:
y_pred = regressor.predict(X_test)
y_pred

array([0, 0, 0, 0])

Get the accuracy

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

1.0